### PR TITLE
Ncm configs rework

### PR DESCRIPTION
**Pull request by mkopec**

### CODE REVIEW

**Comment by mkopec** [comment]
Mostly done, needs to be tested on actual hardware.

**Comment by mkopec** [comment]
Basic tests are passing now so I'm marking this as ready for review @macpijan

**Comment by macpijan** [comment]
@mkopec 

> I added the ability to mix different laptops and test stations like so:

I am fine with this proposal. 

We try to come up with a single regression script: https://github.com/Dasharo/open-source-firmware-validation/blob/develop/scripts/regression.sh to get rid of these platform-specific ones. It might need a few more lines of code to get this working with your proposal. Can you do that?

**Review by macpijan — COMMENTED** [review]
LGTM overall, just left one comment.

**Comment by mkopec** [comment]
@macpijan Added handling of the test station to the regression script, and rebased on `develop`

**Pull request merged**
