### PR TITLE
keywords.robot: added optional timeout argument to Execute Reboot

### PR DESCRIPTION
**Pull request by JanPrusinowski**
keywords.robot: added optional timeout argument to Execute Reboot Command
uefi-setup-menu.robot: removed duplicated keywords

### CODE REVIEW

**Comment by macpijan** [comment]
> those changes should probably be 2 different commits but it's just my opinion.

I agree, commit says about adding timeout, but in fact, we introduce more changes. Please fix @JanPrusinowski

**Comment by JanPrusinowski** [comment]
@m-iwanicki @macpijan I have fixed the commits. One of it is no longer needed.

**Comment by macpijan** [comment]
This MR is in a weird state.

**Comment by macpijan** [comment]
I cannot find anything useful here, closing.

**Pull request closed without merging**
