### PR TITLE
Dcu debug

### PR DESCRIPTION
**Pull request by macpijan**

### CODE REVIEW

**Comment by macpijan** [comment]
Example run for:

* V1610:

```
==============================================================================
Dcu                                                                           
==============================================================================
DCU001.001 Change the UUID :: This test case verifies that the UUI... | PASS |
------------------------------------------------------------------------------
DCU002.001 Change the serial number :: This test case verifies tha... | PASS |
------------------------------------------------------------------------------
```

* V1210:

```
==============================================================================
Dcu                                                                           
==============================================================================
DCU001.001 Change the UUID :: This test case verifies that the UUI... | PASS |
------------------------------------------------------------------------------
DCU002.001 Change the serial number :: This test case verifies tha... | PASS |
------------------------------------------------------------------------------
```

The `DCU003.001` fails now as it requires the display to be connected, which is not at the moment, but it used to work before when it was.

**Comment by JanPrusinowski** [comment]
I'm unable to verify those tests on V1211 as it looks like fw cannot be flashed on this platform anymore and it isnt booting.

**Comment by wiktormowinski** [comment]
@macpijan I pulled the new commit but i seem to have the same problem as before, the test just freezes indefinitely it has been like that for 2h now and I dont think it is gonna unfreeze on its own. Platform: Protectli V1410

**Comment by macpijan** [comment]
@wiktormowinski Freeze where exactly? Any log? How it looks like after you interrupt with Ctrl + C? What was the last keyword?

**Comment by wiktormowinski** [comment]
> @wiktormowinski Freeze where exactly? Any log? How it looks like after you interrupt with Ctrl + C? What was the last keyword?
[dcu-logi-1410.zip](https://github.com/user-attachments/files/16541016/dcu-logi-1410.zip)

**Review by JanPrusinowski — APPROVED** [review]

**Comment by JanPrusinowski** [comment]
Tests pass on v1211. Code looks ok.

**Comment by macpijan** [comment]
Fixes: https://github.com/Dasharo/open-source-firmware-validation/issues/415

**Comment by macpijan** [comment]
Confirmed once again on V1210.

**Pull request merged**
