### PR TITLE
Dts v2

### PR DESCRIPTION
**Pull request by macpijan**

### CODE REVIEW

**Comment by macpijan** [comment]
Relevant tests from Network Boot suite:

```
==============================================================================
Network-Boot                                                                  
==============================================================================
PXE004.001 DTS option is available and works correctly :: This tes... | PASS |
------------------------------------------------------------------------------
PXE007.001 Dasharo Network Boot over https not http :: This test a... | PASS |
------------------------------------------------------------------------------
Network-Boot                                                          | PASS |
2 tests, 2 passed, 0 failed
==============================================================================
```

**Comment by macpijan** [comment]
DTS suite:

```
SNIPEIT_NO=true RTE_IP=127.0.0.1 CONFIG=qemu ./scripts/run.sh ./dasharo-compatibility/dasharo-tools-suite.robot
==============================================================================
Dasharo-Tools-Suite                                                           
==============================================================================
DTS001.001 Booting DTS from USB works correctly :: This test aims ... | SKIP |
DTS001.001 not supported
------------------------------------------------------------------------------
DTS002.001 DTS option Creating Dasharo HCL report works correctly ... | PASS |
------------------------------------------------------------------------------
DTS003.001 DTS option reboot DUT works correctly :: This test aims... | PASS |
------------------------------------------------------------------------------
DTS004.001 DTS accessing shell works correctly :: This test aims t... | PASS |
------------------------------------------------------------------------------
DTS005.001 Flash device from DTS shell by using flashrom works cor... | SKIP |
DTS006.001 not supported
------------------------------------------------------------------------------
DTS006.001 Flash device EC firmware by using DTS built-in script w... | SKIP |
DTS008.001 not supported
------------------------------------------------------------------------------
DTS007.001 Update device EC firmware by using DTS works correctly ... | SKIP |
DTS009.001 not supported
------------------------------------------------------------------------------
DTS008.001 DTS option power-off DUT works correctly :: This test a... | PASS |
------------------------------------------------------------------------------
Dasharo-Tools-Suite                                                   | PASS |
8 tests, 4 passed, 0 failed, 4 skipped
==============================================================================
```

**Comment by macpijan** [comment]
@JanPrusinowski @BeataZdunczyk  Please verify this on MSI when testing RC2.

Then, we can merge this and continue with testing.

**Comment by wiktormowinski** [comment]
works fine now (MSI PRO Z690-a ddr5)

**Pull request merged**
