### PR TITLE
Tests in boot measure.robot will not fail with long irregular boot times

### PR DESCRIPTION
**Pull request by philipandag**

### CODE REVIEW

**Comment by mkopec** [comment]
@philipandag should this be a draft still?

**Comment by philipandag** [comment]
@mkopec sorry, it should not be a draft. I think it is ready for review / merge.

**Review by mkopec — APPROVED** [review]

**Comment by mkopec** [comment]
@philipandag please rebase and resolve merge conflicts

**Comment by philipandag** [comment]
@mkopec rebased and resolved, ready to merge

**Comment by mkopec** [comment]
thanks

**Pull request merged**
