### PR TITLE
[WIP] Qemu secure boot rebase

### PR DESCRIPTION
**Pull request by macpijan**
Adjusting secure boot lib to the latest menu layout.

The 1st goal is to have self- tests covered with scenarios of correctly parsing menus in all available cases.

Further plan for this PR:
- [x] (self-tests) Cover parsing all SB menus in a case where the default keys are provisioned
- [x] (self-tests) Cover parsing all SB menus in a case where the default keys are not provisioned (on 1st QEMU start, or when the Reset Keys option was selected)
- [ ] (self-tests?) Provisioning custom keys and handling file manager 
- [ ]  Make the SBO001 (should already work), SBO002
    - [ ] Depends on OS installation (Ubuntu) 
- [ ] Make the rest of the tests pass as well. These will be more tricky:
    - [ ] Depends on USB drives mounting in QEMU - it is part of this PR: https://github.com/Dasharo/open-source-firmware-validation/pull/88/files
    - [ ] Parsing of the file manager menus is very tricky - I tried to play with that a bit here: https://github.com/Dasharo/open-source-firmware-validation/commit/d4d8976bfce47ed7841805c8a4fd89f9dc4bae4d#diff-b06ff90d8f021dfa2e18d217f3d4c1e6861d6f671893cf292b6718b80227921aR57
- [ ] Make sure to review/rework all kwds in secure boot lib - see this comment: https://github.com/Dasharo/open-source-firmware-validation/pull/95/files#diff-b06ff90d8f021dfa2e18d217f3d4c1e6861d6f671893cf292b6718b80227921aR107 - put useful/tested kwds above that comment, and eventually remove it

### CODE REVIEW

**Comment by macpijan** [comment]
```
robot  -L TRACE -v config:qemu -v rte_ip:127.0.0.1 -v snipeit:no self-tests/secure-boot.robot
==============================================================================
Secure-Boot :: This suite verifies the correct operation of keywords parsin...
==============================================================================
Enter Secure Boot Menu :: Test Enter Secure Boot Menu kwd             | PASS |
------------------------------------------------------------------------------
Enter Secure Boot Menu And Return Construction :: Test Enter Secur... | PASS |
------------------------------------------------------------------------------
Enter Advanced Secure Boot Keys Management :: Test Enter Advanced ... | PASS |
------------------------------------------------------------------------------
Return Secure Boot State :: Test Return Secure Boot State kwd         | PASS |
------------------------------------------------------------------------------
Enable Secure Boot :: Test Enable Secure Boot kwd                     | PASS |
------------------------------------------------------------------------------
Disable Secure Boot :: Test Disable Secure Boot kwd                   | PASS |
------------------------------------------------------------------------------
Enable and Disable Secure Boot Multiple Times :: Test Enabling and... | PASS |
------------------------------------------------------------------------------
Secure-Boot :: This suite verifies the correct operation of keywor... | PASS |
7 tests, 7 passed, 0 failed
==============================================================================
Output:  /home/macpijan/projects/github/dasharo/open-source-firmware-validation/output.xml
Log:     /home/macpijan/projects/github/dasharo/open-source-firmware-validation/log.html
Report:  /home/macpijan/projects/github/dasharo/open-source-firmware-validation/report.html
```

**Comment by pietrushnic** [comment]
@macpijan what version od Dasharo (OVMF) are you using?

```
(venv) [14:28:11] pietrushnic:open-source-firmware-validation git:(qemu-secure-boot-rebase*) $ robot  -L TRACE -v config:qemu -v rte_ip:127.0.0.1 -v snipeit:no self-tests/secure-boot.robot
==============================================================================
Secure-Boot :: This suite verifies the correct operation of keywords parsin...
==============================================================================
Enter Secure Boot Menu :: Test Enter Secure Boot Menu kwd             | PASS |
------------------------------------------------------------------------------
Enter Secure Boot Menu And Return Construction :: Test Enter Secur... | FAIL |
'Secure Boot Mode <Standard Mode>' does not match '^Enable Secure Boot \[.\].*$'
------------------------------------------------------------------------------
Enter Advanced Secure Boot Keys Management :: Test Enter Advanced ... | PASS |
------------------------------------------------------------------------------
Return Secure Boot State :: Test Return Secure Boot State kwd         | PASS |
------------------------------------------------------------------------------
Enable Secure Boot :: Test Enable Secure Boot kwd                     | FAIL |
Option Enable Secure Boot not found in the list
------------------------------------------------------------------------------
Disable Secure Boot :: Test Disable Secure Boot kwd                   | FAIL |
Option Enable Secure Boot not found in the list
------------------------------------------------------------------------------
Enable and Disable Secure Boot Multiple Times :: Test Enabling and... | FAIL |
Option Enable Secure Boot not found in the list
------------------------------------------------------------------------------
Secure-Boot :: This suite verifies the correct operation of keywor... | FAIL |
7 tests, 3 passed, 4 failed
==============================================================================
Output:  /home/pietrushnic/src/3mdeb/dasharo/open-source-firmware-validation/output.xml
Log:     /home/pietrushnic/src/3mdeb/dasharo/open-source-firmware-validation/log.html
Report:  /home/pietrushnic/src/3mdeb/dasharo/open-source-firmware-validation/report.html
```

Also, you left WIP. Do you plan to improve this PR? I guess that expectation is that any UEFI Secure Boot testing should be based on this code.

**Comment by macpijan** [comment]
ok @pietrushnic I know what the problem was. So far I have only tested it with provisioned SB keys.

On real HW, the default keys would be provisooned by default. On QEMU it did not work, so needs to be done manually. Tests should be able to handle both cases correctly. though.

**Comment by pietrushnic** [comment]
@macpijan I have code for resetting the keys

**Comment by macpijan** [comment]
@pietrushnic 

> Also, you left WIP. Do you plan to improve this PR?

Yes, unless you will be faster ;) Maybe you can start with contributing working OS installation, either here or to main branch (we can rebase it then).

I added some checklist in the first comment.

**Comment by pietrushnic** [comment]
@macpijan Thanks, I don't have much time, and we seem to race with this secure boot stuff :)
My goal for today is to pass tests, which means I should reset keys in the self-test IIUC.

**Comment by pietrushnic** [comment]
@macpijan I managed to figure something out using modifications in https://github.com/Dasharo/open-source-firmware-validation/pull/98 I'm getting the following results:

```
robot  -L TRACE -v config:qemu -v rte_ip:127.0.0.1 -v snipeit:no self-tests/secure-boot.robot
==============================================================================
Secure-Boot :: This suite verifies the correct operation of keywords parsin...
==============================================================================
Enter Secure Boot Menu :: Test Enter Secure Boot Menu kwd             | PASS |
------------------------------------------------------------------------------
Check If Enable Secure Boot Can Be Selected :: Test Check If Enabl... | PASS |
------------------------------------------------------------------------------
Enter Secure Boot Menu And Return Construction :: Test Enter Secur... | PASS |
------------------------------------------------------------------------------
Enter Advanced Secure Boot Keys Management :: Test Enter Advanced ... | PASS |
------------------------------------------------------------------------------
Return Secure Boot State :: Test Return Secure Boot State kwd         | PASS |
------------------------------------------------------------------------------
Enable Secure Boot :: Test Enable Secure Boot kwd                     | FAIL |
Option Enable Secure Boot not found in the list
------------------------------------------------------------------------------
Disable Secure Boot :: Test Disable Secure Boot kwd                   | FAIL |
Option Enable Secure Boot not found in the list
------------------------------------------------------------------------------
Enable and Disable Secure Boot Multiple Times :: Test Enabling and... | FAIL |
Option Enable Secure Boot not found in the list
------------------------------------------------------------------------------
Secure-Boot :: This suite verifies the correct operation of keywor... | FAIL |
8 tests, 5 passed, 3 failed
```

**Comment by macpijan** [comment]
In https://github.com/Dasharo/open-source-firmware-validation/pull/95/commits/aa8226a2aa6f2c0a08f59a05fd59395d3a323926 I make sure that parsing SB menu works in both cases (with our without keys). Works == only selectable entries are returned in the menu construction list.

**Comment by macpijan** [comment]
With https://github.com/Dasharo/open-source-firmware-validation/pull/95/commits/7d4979da593632154375aee48035a2a29eb2b40b I can pass all test in both starting states of QEMU (keys are provisioned or reset):

```
==============================================================================
Secure-Boot :: This suite verifies the correct operation of keywords parsin...
==============================================================================
Enter Secure Boot Menu :: Test Enter Secure Boot Menu kwd             | PASS |
------------------------------------------------------------------------------
Enter Secure Boot Menu And Return Construction :: Test Enter Secur... | PASS |
------------------------------------------------------------------------------
Enter Advanced Secure Boot Keys Management :: Test Enter Advanced ... | PASS |
------------------------------------------------------------------------------
Reset To Default Secure Boot Keys :: Test Reset To Default Secure ... | PASS |
------------------------------------------------------------------------------
Erase All Secure Boot Keys :: Test Erase All Secure Boot Keys kwd     | PASS |
------------------------------------------------------------------------------
Secure Boot Menu Parsing With Default Keys                            | PASS |
------------------------------------------------------------------------------
Secure Boot Menu Parsing With Erased Keys :: Test Enter Secure Boo... | PASS |
------------------------------------------------------------------------------
Return Secure Boot State :: Test Return Secure Boot State kwd         | PASS |
------------------------------------------------------------------------------
Make Sure That Keys Are Provisioned :: Test Make Sure That Keys Ar... | PASS |
------------------------------------------------------------------------------
Enable Secure Boot :: Test Enable Secure Boot kwd                     | PASS |
------------------------------------------------------------------------------
Disable Secure Boot :: Test Disable Secure Boot kwd                   | PASS |
------------------------------------------------------------------------------
Enable and Disable Secure Boot Multiple Times :: Test Enabling and... | PASS |
------------------------------------------------------------------------------
Secure-Boot :: This suite verifies the correct operation of keywor... | PASS |
12 tests, 12 passed, 0 failed
```

**Comment by pietrushnic** [comment]
@macpijan any idea why I get other results?

```
robot  -L TRACE -v config:qemu -v rte_ip:127.0.0.1 -v snipeit:no self-tests/secure-boot.robot
==============================================================================                 
Secure-Boot :: This suite verifies the correct operation of keywords parsin...                 
==============================================================================
Enter Secure Boot Menu :: Test Enter Secure Boot Menu kwd             | PASS |                 
------------------------------------------------------------------------------                                                                                                                
Enter Secure Boot Menu And Return Construction :: Test Enter Secur... | PASS |
------------------------------------------------------------------------------                                                                                                                
Enter Advanced Secure Boot Keys Management :: Test Enter Advanced ... | PASS |
------------------------------------------------------------------------------
Reset To Default Secure Boot Keys :: Test Reset To Default Secure ... | PASS |                 
------------------------------------------------------------------------------                 
Erase All Secure Boot Keys :: Test Erase All Secure Boot Keys kwd     | PASS |
------------------------------------------------------------------------------
Secure Boot Menu Parsing With Default Keys                            | PASS |                                                                                                                
------------------------------------------------------------------------------
Secure Boot Menu Parsing With Erased Keys :: Test Enter Secure Boo... | PASS |
------------------------------------------------------------------------------        
Return Secure Boot State :: Test Return Secure Boot State kwd         | PASS |
------------------------------------------------------------------------------
Make Sure That Keys Are Provisioned :: Test Make Sure That Keys Ar... | FAIL |
'['> Erase all Secure Boot Keys', 'Individual key management:', '> PK Options', '> KEK Options', '> DB Options', '> DBX Options', 'v']' does not contain any of 'Enable Secure Boot [ ]' or 'E
nable Secure Boot [X]'                                                                         
------------------------------------------------------------------------------        
Enable Secure Boot :: Test Enable Secure Boot kwd                     | PASS |                 
------------------------------------------------------------------------------
Disable Secure Boot :: Test Disable Secure Boot kwd                   | PASS |
------------------------------------------------------------------------------                 
Enable and Disable Secure Boot Multiple Times :: Test Enabling and... | PASS |
------------------------------------------------------------------------------              
Secure-Boot :: This suite verifies the correct operation of keywor... | FAIL |
12 tests, 11 passed, 1 failed             
==============================================================================
Output:  /home/pietrushnic/src/3mdeb/dasharo/open-source-firmware-validation/output.xml
Log:     /home/pietrushnic/src/3mdeb/dasharo/open-source-firmware-validation/log.html                                                                                                         
Report:  /home/pietrushnic/src/3mdeb/dasharo/open-source-firmware-validation/report.html    
```

**Comment by macpijan** [comment]
@pietrushnic 

Yes, I have some idea.

`['> Erase all Secure Boot Keys', 'Individual key management:', '> PK Options', '> KEK Options', '> DB Options', '> DBX Options', 'v']` - this is the Advanced Confiruation menu, while at this point the test expects to receive Secure Boot Configuration menu (so the one above). The reason is probably that "old" output of this menu was not discarded.
This "flushing" is implemented here: https://github.com/Dasharo/open-source-firmware-validation/pull/95/files#diff-6ad7c5fb97cb1099c7ecd42f15dde3caf06d38b9fe5244afb96394454b6d6bfaR361

We have the same done in `Press Enter` keyword. It has worked fairly reliably so far, but apparently sometimes it can still fail - like need a bit more time. I am not sure how to do it better than just increasing time here, but that would probably help.

**Comment by macpijan** [comment]
The first part of this MR was submitted here: https://github.com/Dasharo/open-source-firmware-validation/pull/117

**Comment by macpijan** [comment]
The current state of SB tests is tracked here: https://github.com/Dasharo/open-source-firmware-validation/pull/118

**Pull request closed without merging**
