### PR TITLE
Add cpb test v2

### PR DESCRIPTION
**Pull request by macpijan**

### CODE REVIEW

**Review by mkopec — APPROVED** [review]

**Comment by pkubaj** [comment]
LGTM.

**Comment by macpijan** [comment]
I want to verify all APU tests can pass before merging. As a first try:

```
==============================================================================
Apu-Configuration-Menu                                                        
==============================================================================
APU001.001 Check if apu2 watchdog option is available :: Check if ... | PASS |
------------------------------------------------------------------------------
APU002.001 Enable apu2 watchdog :: Enable apu2 watchdog with the d... | PASS |
------------------------------------------------------------------------------
APU003.001 Disable apu2 watchdog :: Disable the watchdog after ena... | FAIL |
No match found for 'Save configuration changes?' in 1 minute. Output:
/------------------------------------------------------------------------------\
|                          Dasharo APU Configuration                           |
\------------------------------------------------------------------------------/

   Core Performance Boost     [X]                        Enables/disables FCH
   Enable watchdog            [ ]                        Watchdog Timer during
   Enable PCI Express power   [ ]                        POST.
   management features
                                                         If the timers
                                                         expires, for example
                                                         due to an unexpected
                                                         hang or lockup, the
                                                         platform will be
                                                         reset after specified
                                                         timeout.

    [ Message content over the limit has been removed. ]
          PciRoot(0x0)/Pci(0x11,0x0)/Sata(0x1,0xFFFF,0x0)/HD(1,GPT,96EAD0D5-A232
-11ED-80B7-000DB957A48C,0x28,0x400)
    BLK10: Alias(s):
          PciRoot(0x0)/Pci(0x11,0x0)/Sata(0x1,0xFFFF,0x0)/HD(2,GPT,96EBAD60-A232
-11ED-80B7-000DB957A48C,0x428,0x3A385BD7)
    BLK11: Alias(s):
          PciRoot(0x0)/Pci(0x12,0x0)/USB(0x0,0x0)/USB(0x1,0x0)
    BLK12: Alias(s):
          PciRoot(0x0)/Pci(0x14,0x7)/SD(0x0)
    BLK14: Alias(s):
          PciRoot(0x0)/Pci(0x14,0x7)/SD(0x0)/HD(2,MBR,0xCC76EFAB,0xCE5FFE,0x1E78
02)
    BLK15: Alias(s):
          PciRoot(0x0)/Pci(0x14,0x7)/SD(0x0)/HD(2,MBR,0xCC76EFAB,0xCE5FFE,0x1E78
02)/HD(1,MBR,0x00000000,0xCE6000,0x1E7800)
Press ESC in 4 seconds to skip startup.nsh or any other key to continue.
------------------------------------------------------------------------------
APU004.001 Change apu2 watchdog timeout :: Enable apu2 watchdog wi... | FAIL |
No match found for 'Save configuration changes?' in 1 minute. Output:
ffffffe] size 0x00000000 gran 0x14 bus 03 prefmem
PCI: 00:02.4 20 <- [0x0000000080200000 - 0x00000000802fffff] size 0x00100000 gran 0x14 bus 03 mem
PCI: 00:02.4 assign_resources, bus 3 link: 0
PCI: 03:00.0 10 <- [0x0000000080200000 - 0x000000008021ffff] size 0x00020000 gran 0x11 mem
PCI: 03:00.0 18 <- [0x0000000000003000 - 0x000000000000301f] size 0x00000020 gran 0x05 io
PCI: 03:00.0 1c <- [0x0000000080220000 - 0x0000000080223fff] size 0x00004000 gran 0x0e mem
PCI: 00:02.4 assign_resources, bus 3 link: 0 done
PCI: 00:02.5 1c <- [0x00000000ffffffff - 0x00000000fffffffe] size 0x00000000 gran 0x0c bus 04 io
PCI: 00:02.5 24 <- [0xffffffffffffffff - 0xfffffffffffffffe] size 0x00000000 gran 0x14 bus 04 prefmem
PCI: 00:02.5 20 <- [0x0000000080300000 - 0x00000000803fffff] size 0x00100000 gran 0x14 bus 04 mem
PCI: 00:02.5 assign_resources, bus 4 link: 0
PCI: 04:00.0 10 <- [0x0000000080300000 - 0x000000008030ffff] size 0x0001000...
    [ Message content over the limit has been removed. ]
        0x09 Misc0              : 0x00
        0x0A Misc1              : 0x00
        0x0B Misc2              : 0x00
        0x0C Ser IRQ INTA       : 0x1F
        0x0D Ser IRQ INTB       : 0x1F
        0x0E Ser IRQ INTC       : 0x1F
        0x0F Ser IRQ INTD       : 0x1F
        0x10 SCI                : 0x09
        0x11 SMBUS0             : 0x1F
        0x12 ASF                : 0x1F
        0x13 HDA                : 0x1F
        0x14 FC                 : 0x1F
        0x15 GEC                : 0x1F
        0x16 PerMon             : 0x1F
        0x17 SD                 : 0x10
        0x20 IMC INT0           : 0x05
        0x21 IMC INT1           : 0x1F
        0x22 IMC INT2           : 0x1F
        0x23 IMC INT3           : 0x1F
        0x24 IMC INT4           : 0x
------------------------------------------------------------------------------
APU005.001 Check if disabling CPB decreases performance :: This Te... | FAIL |
Resolving variable '${element.boot_name}' failed: AttributeError: boot_name
------------------------------------------------------------------------------
Apu-Configuration-Menu                                                | FAIL |
5 tests, 2 passed, 3 failed
==============================================================================
```

**Comment by pkubaj** [comment]
Regarding CPB: do you have Ubuntu installed?
The error looks like it's not installed:
`Resolving variable '${element.boot_name}' failed: AttributeError: boot_name`

**Comment by mkopec** [comment]
the boot_name issue was fixed here: https://github.com/Dasharo/open-source-firmware-validation/pull/237/commits/82af8864fb6d5e70aa5e02c5e3e6aca04023eb7f

**Comment by miczyg1** [comment]
Does it pass now on all platforms?

**Review by mkopec — APPROVED** [review]

**Comment by mkopec** [comment]
For completeness, here's a log frop apu6 - had to do some fixes after merging in https://github.com/Dasharo/open-source-firmware-validation/pull/237

[log_apu6.zip](https://github.com/Dasharo/open-source-firmware-validation/files/14756389/log_apu6.zip)

**Pull request merged**
