### PR TITLE
Workaround for Windows Recovery Mode

### PR DESCRIPTION
**Pull request by Psotas**
Workaround for issue: #78

### CODE REVIEW

**Comment by Psotas** [comment]
There is a conflict in the pre-commit. Robotidy makes changes to the code that robocop doesn't allow:
`/code/keywords.robot:207:12 [W] 1015 Each next continuation line should be aligned with the previous one (misaligned-continuation-row)`

**Comment by Psotas** [comment]
Test result:
23 tests
7 times it was rebooted once.
1 time it was rebooted twice.
I think we can leave a maximum of 2 reboots.

**Review by macpijan — APPROVED** [review]

**Comment by macpijan** [comment]
@Psotas I removed this rule in this commit and now the conflict is gone: https://github.com/Dasharo/open-source-firmware-validation/pull/84/commits/d367fcb7e2bcaa369b467e05e242f2506cdc1aa1

I think we may drop it safely.

**Comment by Psotas** [comment]
@macpijan 
> @Psotas I removed this rule in this commit and now the conflict is gone: https://github.com/Dasharo/open-source-firmware-validation/commit/d367fcb7e2bcaa369b467e05e242f2506cdc1aa1
I think we may drop it safely.

Yes, it's just a cosmetic difference.

**Pull request merged**
